{
 "title": "Ark Survival Ascended",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "map_name",
    "label": "map_name",
    "query": {
     "query": "label_values(ark_map_name_info{host=\"$node\"},map_name)"
    }
   },
   {
    "name": "node",
    "label": "Host",
    "query": {
     "query": "label_values(node_uname_info,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Online Players (Cluster Wide)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "ark_active_players{player_name=~\".*\"} == 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Players ${node}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_active_player_count{host=\"$node\"}",
     "legendFormat": "{{ark_active_players_count}}"
    }
   ]
  },
  {
   "title": "Map View",
   "type": "text",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 0 },
   "options": {
    "content": "<div id=\"mapName\" host=${node} data-map=${map_name} style=\"display: none;\"></div>\n<div style=\"position: relative; width: 100%; height: 100%;\">\n    <img id=\"mapImage\" src=\"\" style=\"width: 100%; height: 100%; object-fit: cover;\" alt=\"ARK Map\">\n    <div style=\"position: absolute; top: 20px; left: 20px; color: white; font-size: 40px;\">\n        ARK Map: ${map_name}\n    </div>\n</div>\n\n<script>\n    // Retrieve the map name from the hidden div\n    var mapName = document.getElementById(\"mapName\").getAttribute(\"data-map\");\n    var imageSrc = \"\";\n\n    if (mapName === \"ScorchedEarth_WP\") {\n        imageSrc = \"https://static.wikia.nocookie.net/arksurvivalevolved_gamepedia/images/8/83/Scorched_Earth_Map.png\";\n    } else if (mapName === \"TheIsland_WP\") {\n        imageSrc = \"https://ark.wiki.gg/images/e/e2/The_Island_Map.jpg\";\n    } else if (mapName === \"Aberration_WP\") {\n        imageSrc = \"https://ark.wiki.gg/images/6/68/Aberration_Map.jpg\";\n    } else {\n        imageSrc = \"https://image.api.playstation.com/vulcan/ap/rnd/202310/2502/1751043f9999ae22f2e6293fcf355e596f4183de063619da.png\";\n    }\n\n    // Set the image source dynamically\n    document.getElementById(\"mapImage\").src = imageSrc;\n</script>"
   }
  },
  {
   "title": "Detected Mods",
   "type": "table",
   "gridPos": { "h": 19, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "expr": "ark_installed_mods_info{host=\"$node\"}",
     "legendFormat": "{{mod_id}}"
    }
   ]
  },
  {
   "title": "Startup Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_startup_time_seconds{host=\"$node\"}",
     "legendFormat": "{{startup_time}}"
    }
   ]
  },
  {
   "title": "Map Name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_map_name_info{host=\"$node\"}",
     "legendFormat": "{{map_name}}"
    }
   ]
  },
  {
   "title": "Session Name",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_session_name_info{host=\"$node\"}",
     "legendFormat": "{{session_name}}"
    }
   ]
  },
  {
   "title": "Cluster ID",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_cluster_id_info{host=\"$node\"}",
     "legendFormat": "{{cluster_id}}"
    }
   ]
  },
  {
   "title": "Cluster Directory Override",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ark_cluster_directory_override{host=\"$node\"}",
     "legendFormat": "{{cluster_directory_override}}"
    }
   ]
  }
 ]
}